### ISSUE TITLE
Update CSS to inherit from standard JavaFX properties - p4

### ISSUE THREAD

**Issue by ghost** [io7m/jwheatsheaf#11]
`JWFileChooserConfiguration` is probably the nearest GUI to being a drop-in replacement for JavaFX's bug-ridden `FileChooser` class. JavaFX defines a number of standard CSS classes that can be referenced.

See:

* https://github.com/DaveJarvis/keenwrite/blob/master/src/main/resources/com/keenwrite/skins/haunted_grey.css
* https://docs.oracle.com/javafx/2/css_tutorial/jfxpub-css_tutorial.htm

It would be quite convenient if `JWFileChooserConfiguration` would use the standard JavaFX CSS classes for styling. This is a feature that JavaFX's `FileChooser` lacks (probably because it launches a native file opener).

When the window is displayed, it appears to take on the "Modena Light" theme, instead of the styling from the application's CSS:

![keenwrite-file-chooser](https://user-images.githubusercontent.com/2131950/113980187-05832b80-97fb-11eb-8367-78b808e702b2.png)

**Comment by io7m** [comment]
I'm just glad someone's noticed `jwheatsheaf` exists. :smile: 

I'll take a look at all of the tickets this weekend, we're long overdue for a new release.

**Comment by DaveJarvis** [comment]
> Is there any reason you can't use the CSS URL mechanism?

The reason is kind of philosophical and technical. Imagine if every JavaFX UI component had created its own mechanism for applying stylesheets. In KeenWrite, this might have looked like:

* Update JavaFX CSS style via scene object (this is required regardless).
* Create PreferencesFX and set CSS file via preferences object.
* Create TiwulFX and set CSS file via master docking object.
* Create jwheatsheaf and set CSS file via configuration object.
* Create StyleClassedTextArea and set CSS file via constructor.
* Update ControlsFX to set CSS via Factory/Singleton instance.

That seems counter to the intention of JavaFX's CSS inheritance model. On a technical level, it increases code complexity and incurs copious amounts of architectural duplication. This is the main reason that JavaFX UI components should adopt the application's theme without additional coding.

**Comment by io7m** [comment]
Hm... What actually is the correct way for new components to inherit the existing CSS?

I mean, if you were to define `jwheatsheaf` CSS rules in your own CSS, would `jwheatsheaf` not pick them up right now?

**Comment by DaveJarvis** [comment]
* http://cr.openjdk.java.net/~leifs/8136838/webrev-8u.00/raw_files/new/modules/controls/src/main/resources/com/sun/javafx/scene/control/skin/modena/modena.css
* https://github.com/panemu/tiwulfx-dock/blob/1af4cb5d78d47f0ffc635d7e18cee44712a86d81/src/main/resources/com/panemu/tiwulfx/control/dock/tiwulfx-dock.css#L12

It looks as though `-fx-base`, `-fx-body-color`, `-fx-focus-color`, `-fx-background-color`, and so forth are reusable constants. By changing the colours to refer to those constants, the component should pick up the application's style.

**Comment by io7m** [comment]
I'm not sure that's the whole story. I mean... All `jwheatsheaf` does is define extra CSS IDs and classes so that you can style the elements in your own CSS. It doesn't provide any of its own CSS. The `jwheatsheaf` code should automatically pick up any CSS defined for standard components like buttons automatically... I'm not sure why it apparently isn't. :thinking:

**Comment by DaveJarvis** [comment]
> It doesn't provide any of its own CSS

A few thoughts:

* The `styleClass` attributes in the FXML _shouldn't_ be obliterating the cascading reference to the default theme. Maybe they do? (Unlikely)
* Is the code creating a new `Scene` of its own? If so, maybe the new scene isn't grabbing the application's main scene style? (Also unlikely)
* Does loading FXML require a stylesheet definition, lest it default to Modena?

The FXML is using standard buttons and such, so it's definitely perplexing. The [FilesView](https://github.com/DaveJarvis/keenwrite/blob/master/src/main/java/com/keenwrite/ui/explorer/FilesView.java) class inherits from `BorderPane`, and grabs the scene's colours, but doesn't use FXML. 

In addition to changing the stylesheet for the main scene, I also tried calling:

    Application.setUserAgentStylesheet( ... );

Didn't make any difference. I'm at a loss, but it's not a super-important feature.
