### ISSUE TITLE
Allow inline editing of directory name via hot-key - p2

### ISSUE THREAD

**Issue by ghost** [io7m/jwheatsheaf#13]
Most file choosers have a hot-key that permits users to quickly paste in a different directory. For example:

1. Open file chooser
1. Press `Ctrl+L` (configurable?)
    * File chooser replaces directory drop-down with input field
    * Input field is set to value of directory in the drop-down
    * Input field gains focus
    * Entire input field text is selected
1. Press `Ctrl+v`
    * Input field text is replaced with contents of paste buffer (up until CR/LF)
1. Press `Enter`
    * File chooser navigates to pasted directory (regardless of trailing slash being present)
    * If directory doesn't exist, file chooser attempts to parent directory (no action if non-existing parent)

Bringing up a dialog to change directory is not quite what users have come to expect.

**Comment by io7m** [comment]
Is there a de-facto standard for this? My only experience of file pickers has been on Linux for the past ten years or so, and there's quite a variety of different pickers there. I'm not opposed to this in general.

**Comment by DaveJarvis** [comment]
> Is there a de-facto standard for this?

There is a bit of variety. Some pickers use a breadcrumb list instead of a drop-down for the directory hierarchy (probably because it's fewer clicks and eliminates some redundancy).  Not sure how recent the following screenshots are, but take a look.

I don't know how many of them offer a hot-key to paste a path. On Windows, I think the hot-key is `Alt+d`.

JavaFX

![](https://docs.oracle.com/javafx/2/ui_controls/img/file-chooser-simple.png)

MacOS Finder

![](https://i.i.cbsi.com/cnwk.1d/i/tim/2013/04/05/GoToFolderFilePath.png)

KDE

![](https://i.stack.imgur.com/zXi58.png)

GTK

![](https://i.stack.imgur.com/3REbf.png)

Thunar

![](https://i.stack.imgur.com/fMTNk.png)
