### ISSUE TITLE
Allow automatic closing of resources upon returning selected files - p4

### ISSUE THREAD

**Issue by DaveJarvis** [io7m/jwheatsheaf#25]
https://github.com/io7m/jwheatsheaf/blob/9c341781a8dc13a7aed68e9b9519beb53e0bb1fb/com.io7m.jwheatsheaf.ui/src/main/java/com/io7m/jwheatsheaf/ui/JWFileChoosers.java#L196

What do you think of making a configuration option that, by default automatically closes the thread after a choice is made?

Typically (for Java, anyway), file choosers clean up after themselves without intervention, and without accidental leakage. From the jwheatsheaf [documentation](https://www.io7m.com/software/jwheatsheaf/#documentation):

>  The simplest possible code that can open a file chooser and select at most one file: 

This is a little misleading because it doesn't warn about or show closing the `chooser`. It seems like almost the same amount of effort to silently close upon returning from `showAndWait()` than to update the documentation with a warning to call `close()` so as to prevent leaks.

Another idea is to make `JWFileChooserType` extend `Closable` to get the syntactic benefit of try-with-resources.

P.S.
Thanks for the bug catch in my app!

**Comment by io7m** [comment]
> This is a little misleading because it doesn't warn about or show closing the chooser

That's because you don't need to close the chooser. The `JWFileChoosers` class is a factory of file choosers, defined by the `JWFileChoosersType` interface. The factory itself is a service that's effectively application-scoped and should therefore be closed when the application is closed; individual file chooser instances created from the factory don't need to be closed. The `JWFileChoosersType` interface does extend `Closeable`, so I'm surprised that you didn't get an IDE warning: I make heavy use of `Closeable` and `AutoCloseable` in all of my APIs for both the compile-time warnings and `try-with-resources`.

**Comment by DaveJarvis** [comment]
> I'm surprised that you didn't get an IDE warning

Me too! Closing as [PBCAK](https://www.urbandictionary.com/define.php?term=pbcak).
