### ISSUE TITLE
Allow for overriding button texts

### ISSUE THREAD

**Issue by io7m** [io7m/jwheatsheaf#7]
Allow for specifying custom strings that will be used for buttons.

**Comment by DaveJarvis** [comment]
The JavaFX `FileChooser` offers `showSaveDialog` and `showOpenDialog` methods to control, indirectly, the default button names. Configuring the builder could be a bit more flexible, such as:

``` java
.setFileAccess( FileAccess.EXPORT )
.setFileAccess( FileAccess.IMPORT )
.setFileAccess( FileAccess.OPEN )
.setFileAccess( FileAccess.SAVE )
.setFileAccess( FileAccess.SAVE_AS )
```

**Comment by DaveJarvis** [comment]
Using a `ButtonBar` would be helpful for setting the order that buttons are displayed. For example, see the following short class that overrides the button order:

https://github.com/DaveJarvis/keenwrite/blob/master/src/main/java/com/keenwrite/service/events/impl/ButtonOrderPane.java

For my app, in all cases, the order is fixed to use Windows ordering because that's what most people use, despite having defined the order for the big three:

``` properties
dialog.alert.button.order.mac=L_HE+U+FBIX_NCYOA_R
dialog.alert.button.order.linux=L_HE+UNYACBXIO_R
dialog.alert.button.order.windows=L_E+U+FBXI_YNOCAH_R
```

**Comment by io7m** [comment]
Completed as of https://github.com/io7m/jwheatsheaf/commit/1c8fcbbf757592640dc165de7be2219bb17ccadc.
